Monte Carlo simulation model
npeard/mm-wave-phys pull request #5
Opened 2024-05-13 18:59 UTC by linxin1994

Model for Monte Carlo simulation

2024-05-15 23:12 UTC, neutrinonerd3333 requested changes
Sam and I just took a look through this. The physics looks good except for one point of confusion. We took a long time to check and understand everything; some small changes to coding style would help this going forward. The two main ones are: refactoring almost identical code ("DRY": don't repeat yourself) and taking advantage of `numpy` vectorizing to rewrite all the vector calculations more succinctly (vectorized operations almost always run faster too). Will accept after these changes are made :)

(key to comments: SFB = safe from bugs; ETU = easy to understand; RFC = ready for change)

2024-05-15 23:12 UTC, neutrinonerd3333 commented on models/Monte_Carlo.py
> +
!ETU !RFC: As an example of vectorization, this entire block could be condensed into four lines expressing your intent more clearly:

```python
delta_r = np.sqrt(const.k * T / (m * np.array([omega_H, omega_H, omega_L])**2))
delta_v = np.sqrt(const.k * T / m) * np.ones(3)
r_ensemble = np.random.normal(size=(N_ensemble, 3)) * delta_r
v_ensemble = np.random.normal(size=(N_ensemble, 3)) * delta_v
```

Whenever variables broken up into $x,y,z$ components here, it should be possible to rewrite the code more briefly and clearly in vector form.

2024-05-15 23:12 UTC, neutrinonerd3333 commented on models/Monte_Carlo.py
> +def recature_rate_3d(trap_temp, x_ensemble_t, vx_ensemble_t, y_ensemble, vy_ensemble, z_ensemble, vz_ensemble, t, m, omega_H, omega_L):
!ETU: I think this whole function would vectorize down to just a few very clear lines :)

2024-05-19 17:26 UTC, neutrinonerd3333 commented on models/Monte_Carlo.py
> +        sol = odeint(newton_3d, f0, t, args = (omega_iHO_H, omega_iHO_L,))
Also -- I think that the equations of motion here are integrable, so you could just write $x(t) = x(0) \cosh \omega_x t + x'(0) \omega_x^{-1} \sinh \omega_x t$

2024-07-23 22:45 UTC, npeard commented on models/Monte_Carlo.py
> +    alpha = abs((v + v0)*(v-v0)/v**2)
Add a citation comment in the code to: https://journals.aps.org/pra/pdf/10.1103/PhysRevA.97.053803

2024-07-23 23:10 UTC, neutrinonerd3333 commented on models/Monte_Carlo.py
> +    alpha = abs((v + v0)*(v-v0)/v**2)
Okay, Sam and I looked at this and we now understand what's going on. This should have a cite to the relevant part of the paper and a comment on what it is (`alpha` isn't very descriptive on its own 😅)

2024-07-23 23:12 UTC, neutrinonerd3333 commented on models/Monte_Carlo.py
> +    v0 = wavelength2frequency(D2_line)
Also a correctness issue -- in the referenced paper $\nu_0$ is the mean frequency of the $D$ lines.

2024-07-23 23:57 UTC, npeard approved these changes
changes look good

2024-07-23 23:59 UTC, merged